name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version-file: .fvmrc

      - name: Create .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test --coverage

      - name: Generate coverage report
        uses: mridang/action-test-reporter@464f095756901f11a492504315a766c81b768a76 # v3
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'coverage/lcov.info'
